/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.plywacz.scicalc.gui;

import com.plywacz.scicalc.calcmethods.Calculable;
import com.plywacz.scicalc.calcmethods.TrigonometryMethods;
import com.plywacz.scicalc.calcmethods.TrigonometryMethodsService;
import com.plywacz.scicalc.enums.CalcOperation;
import javax.swing.JList;

/**
 *
 * @author BeGieU
 */
public class UserInterface extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public UserInterface() {
        initComponents();
        calcOperation = CalcOperation.SINUS;
        trigonometryService=new TrigonometryMethodsService();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        evalBtn = new javax.swing.JButton();
        listScrollPane = new javax.swing.JScrollPane();
        funcList = new javax.swing.JList();
        formulaInputTextField = new javax.swing.JTextField();
        textAreaScrollPane = new javax.swing.JScrollPane();
        historyTextArea = new javax.swing.JTextArea();
        menuBar = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        resetMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SciCalc");
        setMinimumSize(new java.awt.Dimension(400, 400));

        evalBtn.setText("Evaluate");

        funcList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "sinus", "cosinus", "tangens", "cotangens", "secant" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        funcList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                funcListMousePressed(evt);
            }
        });
        listScrollPane.setViewportView(funcList);

        formulaInputTextField.setToolTipText("");
        formulaInputTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formulaInputTextFieldActionPerformed(evt);
            }
        });

        historyTextArea.setColumns(20);
        historyTextArea.setRows(5);
        textAreaScrollPane.setViewportView(historyTextArea);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textAreaScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
                    .addComponent(formulaInputTextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(evalBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(listScrollPane)))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
                    .addComponent(textAreaScrollPane))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(evalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(formulaInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        menu.setText("Options");

        resetMenuItem.setText("Reset");
        resetMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                resetMenuItemMousePressed(evt);
            }
        });
        menu.add(resetMenuItem);

        exitMenuItem.setText("Exit");
        exitMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitMenuItemMousePressed(evt);
            }
        });
        menu.add(exitMenuItem);

        menuBar.add(menu);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetMenuItemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetMenuItemMousePressed
        historyTextArea.setText(null);
        formulaInputTextField.setText(null);

    }//GEN-LAST:event_resetMenuItemMousePressed

    private void exitMenuItemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMenuItemMousePressed
        this.dispose();
    }//GEN-LAST:event_exitMenuItemMousePressed

    //handles calc operation choosing
    private void funcListMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_funcListMousePressed
        JList clickedList = (JList) evt.getSource();

        //does an action only when you double click on the list element
        if (evt.getClickCount() == 2) {
            int clickedItemIndex = clickedList.locationToIndex(evt.getPoint());
            if (clickedItemIndex == 0) {
                calcOperation = CalcOperation.SINUS;            
            } else if (clickedItemIndex == 1) {
                calcOperation = CalcOperation.COSINUS;
            } else if (clickedItemIndex == 2) {
                calcOperation = CalcOperation.TANGENS;
            } else if (clickedItemIndex == 3) {
                calcOperation = CalcOperation.COTANGENS;
            } else if (clickedItemIndex == 4) {
                calcOperation = CalcOperation.SECANT;
            } else {
                Object o = clickedList.getModel().getElementAt(clickedItemIndex);
                throw new RuntimeException("non existing item of the list chosen" + o.toString());
            }
        }


    }//GEN-LAST:event_funcListMousePressed

    //starts when enter is pressed
    private void formulaInputTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formulaInputTextFieldActionPerformed
        String formula = formulaInputTextField.getText();
        Double res=trigonometryService.calculate(formula, calcOperation);
        
        System.err.println(formula);
    }//GEN-LAST:event_formulaInputTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserInterface().setVisible(true);
            }
        });
    }

    private CalcOperation calcOperation;
    private final Calculable trigonometryService;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton evalBtn;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JTextField formulaInputTextField;
    private javax.swing.JList funcList;
    private javax.swing.JTextArea historyTextArea;
    private javax.swing.JScrollPane listScrollPane;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenu menu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem resetMenuItem;
    private javax.swing.JScrollPane textAreaScrollPane;
    // End of variables declaration//GEN-END:variables
}
